# Generated by Django 3.1.2 on 2020-11-30 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20201125_1204'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Custormer',
            new_name='Customer',
        ),
    ]
