# Generated by Django 3.1.2 on 2020-12-09 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20201209_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oder',
            name='address',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='oder',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
