# Generated by Django 3.1.2 on 2020-12-14 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20201209_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='oder',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
